enabled: true

env:
  SET_VERSION_OVERRIDE: 4.7-hubspot-$GIT_BRANCH-SNAPSHOT
  MAVEN_OPTS: -Xmx4096m
  MAVEN_ARGS: -DskipTests -am -pl kubernetes-client,kubernetes-model

buildResources:
  cpus: 2
  memoryMb: 5120

buildpack:
  host: git.hubteam.com
  organization: HubSpot
  repository: Blazar-Buildpack-Java
  branch: v2-single-module

provides:
  - name: kubernetes-client
    version: 4.9-hubspot-$GIT_BRANCH-SNAPSHOT
  - name: kubernetes-model
    version: 4.9-hubspot-$GIT_BRANCH-SNAPSHOT
