buildpack:
  name: Blazar-Buildpack-Java-single-module

enabled: true

env:
  SET_VERSION_OVERRIDE: $GIT_BRANCH-SNAPSHOT
  MAVEN_OPTS: -Xmx4096m
  MAVEN_BUILD_ARGS: -DskipTests -am -pl junit/kubernetes-server-mock,kubernetes-model-generator,kubernetes-client,kubernetes-client-api,crd-generator/api,crd-generator/apt,generator-annotations

buildResources:
  cpus: 2
  memoryMb: 5120


provides:
  - name: kubernetes-client
    version: $GIT_BRANCH-SNAPSHOT
