enabled: true

env:
  SET_VERSION_OVERRIDE: $GIT_BRANCH-SNAPSHOT
  MAVEN_OPTS: -Xmx4096m
  MAVEN_ARGS: -DskipTests -am -pl kubernetes-server-mock,kubernetes-model-generator,kubernetes-model-generator/kubernetes-model-apiextensions,kubernetes-client

buildResources:
  cpus: 2
  memoryMb: 5120
