enabled: true

env:
  SET_VERSION_OVERRIDE: $GIT_BRANCH-SNAPSHOT
  MAVEN_OPTS: -Xmx4096m

buildResources:
  cpus: 2
  memoryMb: 5120

buildpack:
  host: git.hubteam.com
  organization: HubSpot
  repository: Blazar-Buildpack-Java
  branch: v2
